config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy', as: 'signout'
  put '/set_per_page', to: 'sessions#set_per_page'
  # resources :users, except: :show, path: '/admin/users'

  resources :users, path: '/admin/users' do
    get 'add_token_to_babili', to: 'users#add_token_to_babili', on: :collection
    get 'get_accessibilities', to: 'users#update_accessibilities', on: :collection
    get 'settings', to: 'users#settings', on: :collection
  end

  namespace :api do
    scope :hooks do
      get 'update_accessibilities', to: 'webhooks#update_user_accessibilities'
      get 'upload_local_user_token', to: 'webhooks#add_token_to_babili'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_token
  sharer

  has_many :memberships, dependent: :destroy
  has_many :groups, through: :memberships
  has_many :record_activities, foreign_key: :actor_id

  validates :name, uniqueness: true

  def self.current
    Thread.current[:current_user]
  end

  def self.current=(usr)
    Thread.current[:current_user] = usr
  end

  # overrides sharer can_edit?
  def can_edit?(resource)
    check_resource(resource)
    (resource.shareable_owner == self ||
      shared_with_me.where(edit: true).exists?(edit: true, resource: resource) ||
      groups.map{|g| g.shared_with_me.where(edit: true).exists?(edit: true, resource: resource) }.include?(true) ||
      app_admin) &&
      !resource.published?
  end

  # overrides sharer can_read?
  def can_read?(resource)
    check_resource(resource)
    resource.published? ||
      resource.shareable_owner == self ||
      shared_with_me.exists?(resource: resource) ||
      groups.map{|g| g.shared_with_me.exists?(resource: resource) }.include?(true) ||
      app_admin
  end

  # extend enki
  def is_owner?
    record_activities.where(activity_type: 'Created').any? || 
    app_admin
  end

  def is_editor?
    shared_with_me.where(edit: true).any? ||
      groups.map{|g| g.shared_with_me.where(edit: true).any?}.include?(true) || 
      app_admin
  end
  # ..

  def is_admin?
    app_admin
  end

  def is_creator?
    app_creator
  end

  def is_publisher?
    app_publisher
  end

  def group_list
    groups.map(&:name).join("; ")
  end
  
  def group_list=(names)
    self.groups = names.reject { |c| c.empty? }.split(";").flatten.map do |n|
      Group.where(name: n).first
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'rest-client'
  before_action :authorize
  before_action :administrative, only: [:index, :update, :destroy]
  before_action :set_user, only: [:update, :destroy]

  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def settings

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.js
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_token_to_babili
    if current_user.regenerate_token
      url = "#{Rails.application.secrets.provider_site}/v1/oread_applications/set_access_token"
      host = request.protocol + request.host
      port = request.port
      begin
        response = RestClient.post url, {token: current_user.token, host: host, port: port}, {:Authorization => "Bearer #{access_token.token}"} 
        redirect_to settings_users_url, notice: response.code == 200 ? "Token for #{JSON.parse(response.body)['name']} received." : 'An error occured.'
      rescue RestClient::ExceptionWithResponse => e
        redirect_to settings_users_url, alert: "The Server ist returning #{e}. Token not sent."
      end
    else
      redirect_to settings_users_url, alert: 'Token not created.'
    end
  end

  def update_accessibilities
    ability = current_user_app_crud_ability
    user = current_user
    user.memberships.destroy_all
    groups = []

    current_user_projects.each do |project|
      group = Group.where(name: project.name).first_or_create! do |g|
        g.gid = project.id
        g.provider = 'babili'
      end
      groups << group
    end

    user.groups = groups
    user.app_admin = ability.can_manage
    user.app_creator = ability.can_create
    user.app_publisher = ability.can_publish
    user.app_commentator = ability.can_comment

    respond_to do |format|
      if user.save
        format.html { redirect_to settings_users_url, notice: 'Your accessibilities have been successfully updated.' }
      else
        format.html { redirect_to settings_users_url, notice: 'An error occured.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:token, :id, :username, :app_admin, :app_commentator, :app_creator, :app_publisher, :group_list => [])
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Username</th>
      <th>Admin</th>
      <th>Commenter</th>
      <th>Creator</th>
      <th>Publisher</th>
      <th>Groups</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= image_tag(user.image_thumb_url, class: 'img-circle') if user.image_thumb_url %>
        </td>
        <td id="user_<%= user.id %>_app_admin">
          <%= link_to user.name, '' %>
        </td>
        <%= simple_form_for [user], remote: true do |f| %>
        <td>
          <%= f.check_box :app_admin, { :onchange => "$(this.form).submit();" } unless user == current_user %>    
        </td>
        <td>
          <%= f.check_box :app_commentator, { :onchange => "$(this.form).submit();" } %>    
        </td>
        <td>
          <%= f.check_box :app_creator, { :onchange => "$(this.form).submit();" } %>    
        </td>
        <td>
          <%= f.check_box :app_publisher, { :onchange => "$(this.form).submit();" } %>    
        </td>
        <td>
          <%= f.input :group_list, 
            label: false,
            collection: Group.all, 
            label_method: :name, 
            value_method: :name,  
            selected: user.groups.map(&:name), 
            input_html: {multiple: true, class: 'groups', style: 'width:100%;', onchange: "$(this.form).submit();" } %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
    $(".groups").select2({
        tags: true,
        tokenSeparators: [';'],
        theme: "bootstrap"
    });
</script>

app/views/users/settings.html.erb
<% title "You are logged in as #{current_user.name}", false %>



<div class="row">
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <%= content_tag :strong, "You are logged in as #{current_user.name}" %>
      </div>
      <div class="panel-body">
        <p>
          Personal API Access Token for this application is: <strong><%= current_user.token %></strong>
        </p>
        <div id="current-user-app-accessibilities" style="margin-top:30px">
          <%= content_tag :h5, "Current accessibilities are:" %>
          <ul>
            <%= content_tag :li, 'manage everything' if current_user.is_admin? %>
            <%= content_tag :li, 'create records' if current_user.is_creator? %>
            <%= content_tag :li, 'read published records or records shared with you' if current_user %>
            <%= content_tag :li, "read records shared with your groups: #{content_tag :strong, current_user.group_list}".html_safe if current_user.groups.any? %>
            <%= content_tag :li, 'update records where edit accessibilities have been assigned to you or your groups' if current_user %>
            <%= content_tag :li, 'remove records which you have created or you have update abilities' if current_user %>
            <%= content_tag :li, 'comment on records' if current_user.app_commentator %>
            <%= content_tag :li, 'publish records' if current_user.is_publisher? %>
          </ul>
        </div>
        <div id ="current-user-search-accessibilities" style="margin-top:30px">
          <%= content_tag :h5, "Connected searchable applications:" %>
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <td>Name</td>
                <td>Search-URL</td>
                <td>Owner</td>
                <td>Connectivity provider</td>
            </thead>
            <tbody>
              <% for app in current_user_search_abilities do %>
                <%= content_tag :tr do %>
                  <%= content_tag :td, link_to(content_tag(:strong, app.name), "#{app.host}#{':'+app.port.to_s if app.port}", target: :blank) %>
                  <%= content_tag :td, app.url %>
                  <%= content_tag :td, link_to(app.owner.name, app.owner.profile_human) %>
                  <%= content_tag :td, link_to("Babili", app.provider_presentation_human) %>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
        <p class="text-muted">
          Personal access token for Babili is: <strong><%= @access_token.token %></strong>
        </p>
      </div>

      <div class="panel-footer">
        <%= link_to fa_icon('caret-square-o-up', text: 'Recreate application token and send to babili'), add_token_to_babili_users_path, class: 'btn btn-xs btn-warning' %>
        <%= link_to fa_icon('caret-square-o-down', text: 'Renew your accessibilities through babili'), get_accessibilities_users_path, class: 'btn btn-xs btn-info' %>
      </div>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-md-7">
    <div class="panel panel-default text-muted">
      <div class="panel-heading">
        <%= content_tag :strong, "Your notification settings" %>
      </div>
      <div class="panel-body">
        todo
      </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<% title "You are logged in as #{current_user.name}" %>

<div class="well">
<p>
  Your personal API Access Token for this application is: <strong><%= current_user.token %></strong>
</p>
  <%= link_to 'Recreate Token and add to babili/oread/search', add_token_to_babili_user_path, class: 'btn btn-sm btn-warning' %>
</div>

<p class="text-muted">
  Your personal access token for Babili is: <strong><%= @access_token.token %></strong>
</p>

app/views/users/update.js.erb
$('#user_<%= @user.id %>_app_admin').append('<p class="text-success small">success</p>');
$('.text-success').fadeOut(1200,function(){ $(this).p.remove(); });